apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.metadata.app }}
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  ports:
  - port: {{ .Values.service.port.mqtt }}
    protocol: TCP
    targetPort: {{ .Values.service.port.mqtt }}
    name: {{ .Values.service.name.mqtt }}
  - port: {{ .Values.service.port.mqttssl }}
    protocol: TCP
    targetPort: {{ .Values.service.port.mqttssl }}
    name: {{ .Values.service.name.mqttssl }}
  - port: {{ .Values.service.port.prometheus }}
    protocol: TCP
    targetPort: {{ .Values.service.port.prometheus }}
    name: {{ .Values.service.name.prometheus }}
  - port: {{ .Values.service.port.empd }}
    protocol: TCP
    targetPort: {{ .Values.service.port.empd }}
    name: {{ .Values.service.name.empd }}
  - port: {{ .Values.service.port.websockets }}
    protocol: TCP
    targetPort: {{ .Values.service.port.websockets }}
    name: {{ .Values.service.name.websockets }}
  selector:
    app: {{ .Values.metadata.app }}
  type: {{ .Values.service.type }} 
