apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vernemq-dep
  name: vernemq-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vernemq-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vernemq-dep
    spec:
      containers:
      - image: asia-docker.pkg.dev/gcp-iot-core-361019/iot-core-dev/vernemq:e9db44eb19cc61ae5426d00558e2859923a88a77
        name: vernemq
        ports:
        - containerPort: 8888
          name: ui
        - containerPort: 1883
          name: mqtt
        - containerPort: 8883
          name: ssl
        - containerPort: 4369
          name: empd
        - containerPort: 44053
          name: msg
        - containerPort: 9100
          name: erlan1
        - containerPort: 9101
          name: erlan2
        env:
          - name: DOCKER_VERNEMQ_ACCEPT_EULA
            value: "yes"
          - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
            value: "off"
          - name: DOCKER_VERNEMQ_PLUGINS.vmq_acl
            value: "off"
          - name: DOCKER_VERNEMQ_PLUGINS.vmq_passwd
            value: "off"
          - name: DOCKER_VERNEMQ_PLUGINS.vmq_webhooks
            value: "on"
          - name: DOCKER_VERNEMQ_VMQ_WEBHOOKS.mywebhook1.hook
            value: "on_subscribe"
          - name: DOCKER_VERNEMQ_VMQ_WEBHOOKS.mywebhook1.endpoint 
            value: "http://state-manage.default.svc.cluster.local:8094/subscribeHook"
          - name: DOCKER_VERNEMQ_VMQ_WEBHOOKS.mywebhook2.hook
            value: "auth_on_register"
          - name: DOCKER_VERNEMQ_VMQ_WEBHOOKS.mywebhook2.endpoint 
            value: "http://dev-gw-auth.default.svc.cluster.local:8094/device/authenticate"
          - name: DOCKER_VERNEMQ_VMQ_WEBHOOKS.mywebhook3.hook
            value: "auth_on_publish"
          - name: DOCKER_VERNEMQ_VMQ_WEBHOOKS.mywebhook3.endpoint  
            value: "http://dev-gw-auth.default.svc.cluster.local:8094/device/pubAuthorize"
          - name: DOCKER_VERNEMQ_VMQ_WEBHOOKS.mywebhook4.hook
            value: "auth_on_subscribe"
          - name: DOCKER_VERNEMQ_VMQ_WEBHOOKS.mywebhook4.endpoint  
            value: "http://dev-gw-auth.default.svc.cluster.local:8094/device/subAuthorize"
           
